# -*- encoding : utf-8 -*-

# DO NOT EDIT THIS FILE! (Create new task(s) using tasks/*.rake convention

$LOAD_PATH.unshift '.'

Dir[File.expand_path(__FILE__ + '/..') + '/tasks/*.rake' ].each do |f|
  load f
end
